<h1>Slim says you HELLO!</h1>
<p>...from the template ^-^</p>
<div>
    <form action="/" method="get">
    <input type="search" name="search" value="<?= $search ?>" placeholder="Search something" />
    <input type="submit" value="Search" />
    </form>

    <?php if ($foundData): ?>
    <div class="bordered">
        <p>Hooray! You found something ^-^</p>
        <?php foreach ($foundData as $value): ?>
            <p><i><?= $value ?></i></p>
        <?php endforeach; ?>
    </div>
     <?php endif; ?>

</div>
<div>
<ul>Also you can follow by these links:</ul>
<?php foreach ($links as ['name' => $name, 'path' => $path]): ?>
    <li><a href="<?= $path ?>"><?= $name ?></a></li>
<?php endforeach; ?>
</div>