<!DOCTYPE html>
<html>
<head>
    <title><?= $title ?></title>
    <style>
        .current-page a {
            background-color: green;
            padding: 3px 5px;
            border-radius: 50%;
            color: #fff;
            font-weight: bold;
        }
        body {
            max-width: 620px;
            margin: 0 auto;
            padding: 5px 0;
            background-color: #eee;
        }
     </style>
</head>
<body>
    <?= $content ?>
</body>
</html>