<h1>Adding new user</h1>

<form action="/users" method="post">
    <div>
        <label>Username:
            <input type="text" name="user[name]">
        </label>
    </div>
    <div>
      <label>E-mail:
            <input type="email" required name="user[email]">
        </label>
    </div>
    <div>
        <label>Phone:
              <input type="tel" required name="user[phone]">
          </label>
      </div>
    <input type="submit" value="Sign Up">
  </form>