<?php if ($users): ?>
<table>
    <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>PHONE</th>
    </tr>
    <?php foreach ($users as $user): ?>
    <tr>
        <td><?= $user['id'] ?></td>
        <td><?= $user['name'] ?></td>
        <td><?= $user['phone'] ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<div>
    <a href="/users/new">Add new user</a>
</div>
<div>
    <a href="/">Homepage</a>
</div>